### ISSUE TITLE
Feature Request: Custom Nodes with custom Parameters

### ISSUE THREAD

**Issue by garv3** [andrei-tatar/node-red-contrib-smartnora#43] opened 2021-05-20 00:38 UTC
First of all I want to thank you for this great integration.

What is missing is a node supporting a custom command. One way I currently use to start custom flows is the Scene node. But there is a catch: I have to say "Start My Node". Just saying "My Node" won't start it.
Additionally it would be great to have custom parameters that you can say in addition. For example to have my TV be turned on and switched to a channel and my AVR be set to a desired volume I would have to use several commands right now.

I would love to be able to use custom commands like "Show {channel name} [with {50}% volume]". Therefore We could use a custom node that enables us to specify the command and parameters (which we could then use in the flow).

Is this possible? That would be awesome!

Thanks and best regards

**Comment by andrei-tatar** [comment] 2021-05-20 12:49
This might be a duplicate of #25 

> But there is a catch: I have to say "Start My Node". Just saying "My Node" won't start it.

I think it's possible to define custom routines that start on what voice match you want.

> Is this possible? That would be awesome!

Unfortunately it's not possible using the smart home action. I would be possible using a conversational action but that's not in the near future plan for NORA.

**Comment by garv3** [comment] 2021-05-20 15:22
Thanks for the clearification.

I read #25 before posting but thought it would be another request because this would not require conversational actions.
Obviously it does, so my apologies.

I know about the routines but these have to be set up manually which can result in a pretty long and annoying process. Especially if you have to do it for multiple persons in your home since routines are linked to the personal accounts and not the assistant or home.

**Comment by andrei-tatar** [comment] 2021-05-21 08:42
I'll close this issue for now and leave #25

**Closed by andrei-tatar** 2021-05-21 08:43 UTC
