### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by mattheijer** [andrei-tatar/node-red-contrib-smartnora#242] opened 2023-01-11 14:57 UTC
Describe the problem here...

My user id is: suMqVf7p00QvPvHEqS4InixIxna2

The time on the machine is alright,
But still smart nora has no connection witch nod-red ?

**Comment by andrei-tatar** [comment] 2023-01-12 15:35
Duplicate of #241

**Closed by andrei-tatar** 2023-01-12 15:35 UTC
