### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by manojgupta89** [andrei-tatar/node-red-contrib-smartnora#145] opened 2022-01-06 17:48 UTC
Till now it is not solved. I can control all the devices from Smart-nora dashboard. But not from Google home app or Google assistant. Please help..

My user id is: FZ6tZaTdtKehQADxhwroWZnp3Gj2

**Comment by andrei-tatar** [comment] 2022-01-07 09:58
Duplicate of #140

**Closed by andrei-tatar** 2022-01-07 09:58 UTC
